// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'services/device_service.dart';
import 'services/firebase_service.dart';
import 'screens/home_screen.dart';
import 'screens/admin_screen.dart';
import 'utils/app_theme.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Force portrait only
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Set status bar style
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
  ));

  // 🔒 Enable screenshot/recording block immediately
  await DeviceService().enableContentShield();

  // Initialize FCM
  await FirebaseService().initFCM();

  runApp(const MarketMindApp());
}

class MarketMindApp extends StatelessWidget {
  const MarketMindApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
    title: AppConstants.appName,
    debugShowCheckedModeBanner: false,
    theme: AppTheme.darkTheme,
    initialRoute: '/',
    routes: {
      '/':      (_) => const HomeScreen(),
      '/admin': (_) => const AdminScreen(),
    },
  );
}
